In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
recom = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header=None)
recom.head()

0      1      2      3      4    ...    96     97     98     99     100
0   74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1  100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2   49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3   48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4   91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60

[5 rows x 101 columns]

In [ ]:
recom.describe().transpose()

count       mean        std    min     25%    50%    75%    max
0    24983.0  72.467478  21.859600  36.00  53.000  72.00  100.0  100.0
1    24983.0  34.401435  46.707059  -9.95  -0.150   5.05   99.0   99.0
2    24983.0  27.094089  44.228006  -9.95  -2.180   3.69   99.0   99.0
3    24983.0  33.263717  46.747535  -9.95  -1.145   4.66   99.0   99.0
4    24983.0  36.244936  48.812967  -9.95  -3.350   3.45   99.0   99.0
..       ...        ...        ...    ...     ...    ...    ...    ...
96   24983.0  58.541104  48.130562  -9.95   3.300  99.00   99.0   99.0
97   24983.0  58.017246  48.164681  -9.95   3.590  99.00   99.0   99.0
98   24983.0  57.061650  48.717455  -9.95   2.670  99.00   99.0   99.0
99   24983.0  55.753357  49.237139  -9.95   1.335  99.00   99.0   99.0
100  24983.0  60.138090  47.913531  -9.95   3.930  99.00   99.0   99.0

[101 rows x 8 columns]

In [ ]:
recom_nan = recom.replace(99, np.nan)

In [ ]:
recom_nan.isna().sum()

0         81
1       8531
2       6799
3       8341
4       9375
       ...  
96     14613
97     14463
98     14317
99     14073
100    15040
Length: 101, dtype: int64

In [ ]:
len(recom[0].unique())

65

In [ ]:
recom_nan.drop(columns=0, axis=1, inplace=True)

In [ ]:
recom_nan.head()

1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 100 columns]

In [ ]:
recom_nan.mean().sort_values(ascending=True)

58   -3.833880
16   -3.104818
44   -2.111891
57   -1.990664
13   -1.762882
        ...   
32    3.155988
27    3.189821
36    3.312500
89    3.574720
50    3.665085
Length: 100, dtype: float64

In [ ]:
arr_1 = recom_nan.values

In [ ]:
np.where(arr_1!= 99)

(array([    0,     0,     0, ..., 24982, 24982, 24982]),
 array([ 0,  1,  2, ..., 97, 98, 99]))

In [ ]:
def helper_function(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(~np.isnan(orig))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [ ]:
new_arr, idx = helper_function(arr_1)

In [ ]:
arr_1[idx[0][0], idx[1][0]]

-5.63

In [ ]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [ ]:
recom.groupby(0).count()

1     2     3     4     5     6    ...   95    96    97    98    99    100
0                                        ...                                    
36    482   482   482   482   482   482  ...   482   482   482   482   482   482
37    409   409   409   409   409   409  ...   409   409   409   409   409   409
38    413   413   413   413   413   413  ...   413   413   413   413   413   413
39    391   391   391   391   391   391  ...   391   391   391   391   391   391
40    407   407   407   407   407   407  ...   407   407   407   407   407   407
..    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
96     68    68    68    68    68    68  ...    68    68    68    68    68    68
97     60    60    60    60    60    60  ...    60    60    60    60    60    60
98     71    71    71    71    71    71  ...    71    71    71    71    71    71
99     81    81    81    81    81    81  ...    81    81    81    81    81    81
100  7200  7200  7200  7200  7200  7200  ...  7200  7200  7200  7200  7200  7200

[65 rows x 100 columns]

In [ ]:
users = recom[0].unique()
users

array([ 74, 100,  49,  48,  91,  47,  72,  36,  51,  53,  55,  50,  67,
        60,  54,  46,  38,  41,  73,  92,  89,  71,  40,  45,  62,  63,
        61,  65,  68,  69,  37,  56,  66,  64,  82,  57,  75,  88,  86,
        43,  83,  93,  94,  44,  59,  39,  58,  70,  78,  97,  90,  84,
        98,  96,  52,  80,  42,  81,  76,  79,  85,  77,  95,  87,  99])

In [ ]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 5) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [ ]:
n_latent_factors = 4

user_ratings = recom_nan.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [ ]:
err  =[]
for u, i in zip(*idx):
  err.append(predict_rating(u,i) - user_ratings[u,i])
print('MSE of validation set: ', (np.array(err)**2).mean())

MSE of validation set:  27.663525299933795


In [ ]:
test_idx = np.where(np.isnan(user_ratings))
for u, i in zip(*test_idx):
  print('Prediction for {} user_id for item_id {} is {}'.format(u, i, predict_rating(u,i)))

Streaming output truncated to the last 5000 lines.
Prediction for 24812 user_id for item_id 92 is 1.000588068062231
Prediction for 24812 user_id for item_id 93 is 0.8899621287467092
Prediction for 24812 user_id for item_id 94 is 0.6806186741670722
Prediction for 24812 user_id for item_id 95 is 0.6665937577246955
Prediction for 24813 user_id for item_id 70 is 1.156661115230541
Prediction for 24813 user_id for item_id 71 is 0.8863218157734349
Prediction for 24813 user_id for item_id 72 is 1.390015308825449
Prediction for 24813 user_id for item_id 73 is 1.1293066111423629
Prediction for 24813 user_id for item_id 74 is 0.9543116935608417
Prediction for 24813 user_id for item_id 75 is 1.2757984854197755
Prediction for 24813 user_id for item_id 76 is 0.8671079551021188
Prediction for 24813 user_id for item_id 77 is 0.45298659076792486
Prediction for 24813 user_id for item_id 78 is 0.9859448777128659
Prediction for 24813 user_id for item_id 79 is 0.6176151522939326
Prediction for 24813 user_i

In [ ]:
test_idx

(array([    0,     0,     0, ..., 24982, 24982, 24982]),
 array([70, 71, 72, ..., 97, 98, 99]))

In [ ]:
num_iter = 100
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 5), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

Iteration 0/100:	MSE=25.674667
Iteration 5/100:	MSE=24.482733
Iteration 10/100:	MSE=23.810884
Iteration 15/100:	MSE=22.963158


In [ ]:
recom_nan.iloc[55,13]

In [ ]:
df_items = pd.read_excel('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true')
df_users = pd.read_excel('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true', sheet_name=1)

In [ ]:
df_users.set_index('User', inplace=True)

In [ ]:
df_items[df_items['Factor15'] == df_items['Factor15'].min()]

In [ ]:

items_latent = df_items.drop('Title', axis=1).values



In [ ]:
user_latent = df_users.values

In [ ]:
user_latent.shape

In [ ]:
items_latent.shape

In [ ]:
def predict_movie_rating(user, movie):
  user_arr = df_users.loc[user].values
  movie_arr = df_items.loc[movie].drop('Title').values
  return user_arr.dot(movie_arr)

In [ ]:
def top_n_recommendation(user, n):
  pred = {}
  for movie in df_items.index:
    pred[movie] = predict_movie_rating(user, movie)
  pred = dict(sorted(pred.items(), key=lambda kv: kv[1], reverse=True))
  movies = list(pred.keys())
  return movies[:n]

In [ ]:
predict_movie_rating(783, 807)

In [ ]:
predict_movie_rating(156, 9331)

In [ ]:
top_n_recommendation(4940, 3)

In [ ]:
df_items.loc[top_n_recommendation(1882, 2)]['Title']